name: PHP

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  PHP:
    runs-on: ubuntu-22.04
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
        env:
          runner: ubuntu-22.04
