name: PHP

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  PHP:
    runs-on: ubuntu-20.04
    env:
      PHP_VERSION: 8.2
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
